# Generated by Django 2.2.2 on 2020-11-29 17:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='课程名称')),
                ('term', models.CharField(max_length=100, verbose_name='上课学期')),
                ('course_time', models.IntegerField(verbose_name='课程学时')),
                ('course_grade', models.IntegerField(verbose_name='课程学分')),
                ('teacher', models.CharField(max_length=20, verbose_name='授课教师')),
                ('address', models.CharField(max_length=200, verbose_name='上课时间地点')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.DepartmentInfo', verbose_name='所属学院')),
            ],
            options={
                'verbose_name': '课程信息',
                'verbose_name_plural': '课程信息',
            },
        ),
    ]
