# Generated by Django 2.2.2 on 2020-12-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinfo',
            name='course_cj',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='课程成绩'),
        ),
    ]
