# Generated by Django 2.2.2 on 2020-12-04 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_courseinfo_course_cj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseinfo',
            name='course_cj',
        ),
    ]
