# Generated by Django 2.2.2 on 2020-12-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_courseinfo_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, '公共基础课'), (2, '公共选修课'), (3, '专业基础课'), (4, '专业方向课'), (5, '专业选修课')], null=True, verbose_name='课程类别'),
        ),
    ]
