# Generated by Django 2.2.2 on 2020-12-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201201_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, '全日制专业学位硕士'), (2, '全日制学业学位硕士'), (3, '全日制本科学位')], null=True, verbose_name='学生类别'),
        ),
    ]
