# Generated by Django 2.2.2 on 2020-11-29 17:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='学院名称')),
                ('desc', models.CharField(blank=True, max_length=300, null=True, verbose_name='学院简介')),
                ('student_num', models.IntegerField(default=0, verbose_name='院学生人数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '学院信息',
                'verbose_name_plural': '学院信息',
            },
        ),
        migrations.CreateModel(
            name='MajorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='专业名称')),
                ('student_num', models.IntegerField(default=0, verbose_name='专业学生人数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.DepartmentInfo', verbose_name='所属学院')),
            ],
            options={
                'verbose_name': '专业信息',
                'verbose_name_plural': '专业信息',
            },
        ),
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='班级名称')),
                ('student_num', models.IntegerField(default=0, verbose_name='班级人数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.MajorInfo', verbose_name='所属专业')),
            ],
            options={
                'verbose_name': '班级信息',
                'verbose_name_plural': '班级信息',
            },
        ),
    ]
