# Generated by Django 2.2.2 on 2020-11-29 17:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300, verbose_name='奖惩情况')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '奖惩信息',
                'verbose_name_plural': '奖惩信息',
            },
        ),
        migrations.CreateModel(
            name='ScourseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='选课时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseInfo', verbose_name='所选课程')),
            ],
            options={
                'verbose_name': '选课信息',
                'verbose_name_plural': '选课信息',
            },
        ),
    ]
