# Generated by Django 2.2.2 on 2020-11-29 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('behavior', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scourseinfo',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='选课学生'),
        ),
        migrations.AddField(
            model_name='rewardinfo',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='获奖学生'),
        ),
    ]
