# Generated by Django 2.2.2 on 2020-12-03 20:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behavior', '0002_auto_20201129_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_student', models.IntegerField(default=0, verbose_name='消息学生')),
                ('message_content', models.CharField(max_length=300, verbose_name='消息内容')),
                ('messa_status', models.BooleanField(default=False, verbose_name='消息状态')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '学生消息信息',
                'verbose_name_plural': '学生消息信息',
            },
        ),
    ]
