# Generated by Django 2.2.2 on 2020-12-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behavior', '0004_auto_20201203_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='scourseinfo',
            name='course_cj',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='课程成绩'),
        ),
    ]
