# Generated by Django 2.2.2 on 2020-12-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behavior', '0007_auto_20201213_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scourseinfo',
            name='type',
            field=models.CharField(blank=True, choices=[('选课', '选课'), ('退选', '退选')], default='申请', max_length=20, null=True, verbose_name='申请类型'),
        ),
    ]
