# Generated by Django 2.2.2 on 2020-12-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behavior', '0009_auto_20201213_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scourseinfo',
            name='type',
            field=models.CharField(choices=[('选课', '选课'), ('退选', '退选')], default='选课', max_length=20, verbose_name='申请类型'),
        ),
    ]
