# Generated by Django 2.2.2 on 2020-12-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behavior', '0011_remove_scourseinfo_is_choose'),
    ]

    operations = [
        migrations.AddField(
            model_name='scourseinfo',
            name='reason',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='申请原因'),
        ),
        migrations.AlterField(
            model_name='scourseinfo',
            name='type',
            field=models.CharField(blank=True, choices=[('选课', '选课'), ('退选', '退选'), ('已选', '已选')], max_length=20, null=True, verbose_name='申请类型'),
        ),
    ]
