# Generated by Django 2.2.2 on 2020-12-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behavior', '0012_auto_20201213_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scourseinfo',
            name='type',
            field=models.CharField(blank=True, choices=[('申请', '申请'), ('退选', '退选'), ('已选', '已选')], max_length=20, null=True, verbose_name='申请类型'),
        ),
    ]
